show_downloads: true
theme: jekyll-theme-architect
title: <img src="https://raw.githubusercontent.com/spelunky-fyi/Spelunky-2-Font-Editor/main/images/site-logo.png" width="690">
description: Spelunky 2 Sprite Font Editor
github:
  zip_url: https://github.com/spelunky-fyi/Spelunky-2-Font-Editor/releases
  another_url: https://github.com/spelunky-fyi/Spelunky-2-Font-Editor/releases
